
PROGS  = notebook
SOURCES = Notebook.hs

all : $(PROGS)

notebook : Notebook.hs
	$(HC_RULE)

HC_RULE = $(HC) --make $< -o $@ $(HCFLAGS)

clean:
	rm -f $(SOURCES:.hs=.hi) $(SOURCES:.hs=.o) $(PROGS)

HC=ghc
