-- GENERATED by C->Haskell Compiler, version 0.11.1 "Powder Snow", 1 Feb 2003 (C->HS binding)
-- ** Edit the orignal .chs file instead!

{-# LINE 1 "Cpp.chs" #-}
-- -*-haskell-*-

module Cpp
where

#if (VERSION == 1)

-- this does not match the C definition
--
foo :: Int -> Int
foo = {#call fooC#}{-# LINE 11 "Cpp.chs" #-}


#else

-- this does
--
foo :: Int -> Int -> Int
foo = {#call fooC#}{-# LINE 18 "Cpp.chs" #-}


#end


-- C code

#c

#define VERSION 2

int fooC (int, int);

#endc

